### ISSUE TITLE
Import bricht ständig ab

### ISSUE THREAD

**Issue by ABreini** [solectrus/csv-importer#224]
Hallo zusammen,

ich versuche derzeit verzweifelt den Import der CSV Daten durchzuführen. 
Die Daten liegen alle entsprechend auf dem RasberryPI (Vers. 5).

Nach Start des Skripts bricht dieses nach Import von 2-3 CSV-Dateien regelmäßig ab. 

Wo könnte das Problem / die Lösung liegen?

Danke im Voraus

Hier die Fehlermeldung:
```powershell
pi@pi:~/solectrus $ docker run -it --rm \
           --env-file .env \
           --mount type=bind,source="$PWD/csv",target=/data,readonly \
           --network=solectrus_default \
           ghcr.io/solectrus/csv-importer
Unable to find image 'ghcr.io/solectrus/csv-importer:latest' locally
latest: Pulling from solectrus/csv-importer
94747bd81234: Already exists
00096a3b09ce: Already exists
45efde9dee28: Already exists
450984116bfe: Already exists
50c2852d8074: Already exists
7ac01ecbbe4a: Pull complete
4914814a227a: Pull complete
678d13ca7b04: Pull complete
Digest: sha256:54fd949b7e76ad0faff1a794546f9e4588d1bddaae187a99323b3b18e6d3d8c2
Status: Downloaded newer image for ghcr.io/solectrus/csv-importer:latest
CSV importer for SOLECTRUS, Version 0.4.0, built at 2024-06-02T12:33:48.529Z
https://github.com/solectrus/csv-importer
Copyright (c) 2020-2024 Georg Ledermann and contributors, released under the MIT License

Using Ruby 3.3.2 on platform aarch64-linux-musl
Pushing to InfluxDB at http://influxdb:8086, bucket solectrus
Using time zone Europe/Berlin

Importing data from /data ...
Importing /data/csv/S41943351095585795540096323-week-1-2024.csv using SenecRecord adapter... Done, 2007 points imported
Importing /data/csv/S41943351095585795540096323-week-10-2024.csv using SenecRecord adapter... Done, 2008 points imported
Importing /data/csv/S41943351095585795540096323-week-12-2024.csv using SenecRecord adapter...bundler: failed to load command: app/main.rb (app/main.rb)
/usr/local/bundle/gems/influxdb-client-3.1.0/lib/influxdb2/client/default_api.rb:106:in `_request': unexpected error writing points to database: timeout (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-3.1.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-3.1.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-3.1.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /csv-importer/app/flux_writer.rb:17:in `push'
        from /csv-importer/app/flux_writer.rb:11:in `push'
        from /csv-importer/app/import.rb:49:in `process'
        from /csv-importer/app/import.rb:15:in `block in run'
        from /csv-importer/app/import.rb:14:in `each'
        from /csv-importer/app/import.rb:14:in `run'
        from app/main.rb:24:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `load'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli/exec.rb:23:in `run'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli.rb:455:in `exec'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli.rb:35:in `dispatch'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/cli.rb:29:in `start'
        from /usr/local/bundle/gems/bundler-2.5.11/exe/bundle:28:in `block in <top (required)>'
        from /usr/local/bundle/gems/bundler-2.5.11/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /usr/local/bundle/gems/bundler-2.5.11/exe/bundle:20:in `<top (required)>'
        from /usr/local/bundle/bin/bundle:25:in `load'
        from /usr/local/bundle/bin/bundle:25:in `<main>'
```

**Comment by ledermann** [comment]
InfluxDB vielleicht überlastet? Versuch es mal mit `IMPORT_PAUSE`, um nach jeder CSV eine kleine Pause einzulegen:

```
docker run -it --rm \
           --env-file .env \
           --env IMPORT_PAUSE=5 \
           --mount type=bind,source="$PWD/csv",target=/data,readonly \
           --network=solectrus_default \
           ghcr.io/solectrus/csv-importer
```

Wir hatten ein solches Phänomen in #5 schon mal, da war es letztendlich aber eine kaputte SD-Karte.

**Comment by ABreini** [comment]
Also hier die Antwort:

Es lag tatsächlich schlicht an der kaputten SD-Karte. 
Neue gekauft und eingelegt. Alles funktioniert wieder. 

Auch die Installation lief wieder reibungslos und  schnell ab. 


Danke für den Hinweis und deine schnelle Antwort.

**Comment by ledermann** [comment]
Prima, danke für die Rückmeldung!
