### ISSUE TITLE
Sungrow: Field type conflict float vs. integer

### ISSUE THREAD

**Issue by holiday-sunrise** [solectrus/csv-importer#54]
```
Importing data from /data ...
Importing /data/Tagesbericht_Drexler-50389_20230628212844.csv... bundler: failed to load command: app/main.rb (app/main.rb)
/usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:106:in `_request': failure writing points to database: partial write: field type conflict: input field "bat_power_minus" on measurement "SENEC" is type float, already exists as type integer dropped=190 (InfluxDB2::InfluxError)
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/default_api.rb:59:in `_post_text'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:214:in `write_raw'
        from /usr/local/bundle/gems/influxdb-client-2.9.0/lib/influxdb2/client/write_api.rb:186:in `write'
        from /csv-importer/app/flux_writer.rb:17:in `push'
        from /csv-importer/app/flux_writer.rb:11:in `push'
        from /csv-importer/app/import.rb:50:in `process'
        from /csv-importer/app/import.rb:17:in `block in run'
        from /csv-importer/app/import.rb:16:in `each'
        from /csv-importer/app/import.rb:16:in `run'
        from app/main.rb:23:in `<top (required)>'
        from /usr/local/bundle/gems/bundler-2.4.15/lib/bundler/cli/exec.rb:58:in `load'
```

[Tagesbericht_Drexler-50389_20230628212844.csv](https://github.com/solectrus/csv-importer/files/11926457/Tagesbericht_Drexler-50389_20230628212844.csv)

**Comment by ledermann** [comment]
Danke für den Bugreport! Hier gab es einen Datentyp-Konflikt zwischen den bereits in InfluxDB vorhandenen Daten (`Integer`) mit den importierten, die fälschlicherweise als `Float` geschrieben wurden. 

Das habe ich jetzt korrigiert. Mit `v0.3.1` sollte es jetzt klappen.

**Comment by holiday-sunrise** [comment]
Da warst du schneller 😉
